### ISSUE TITLE
Wrap each_child/children_if & each_clip/clip_if instead of reimplementing

### ISSUE THREAD

**Issue by KarthikRIyer** [OpenTimelineIO/OpenTimelineIO-Java-Bindings#21]
Right now, the bindings reimplement `eachChild/eachClip`.

[This](https://github.com/PixarAnimationStudios/OpenTimelineIO/pull/926) PR introduces these functions in the C++ core (`each_child` renamed to `children_if` & `each_clip` renamed to `clip_if`). Also, these functions return `std::vector` instead of iterators.

We should wrap these functions to maintain consistency.

The OTIO dependency with this change was landed in #20

**Comment by jradha11** [comment]
@KarthikRIyer can I start working on this issue?

**Comment by KarthikRIyer** [comment]
Yes!
